export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";


export const ADMIN_HOME_REQUEST = "ADMIN_HOME_REQUEST";
export const ADMIN_HOME_FAIL = "ADMIN_HOME_FAIL";
export const ADMIN_HOME_SUCCESS = "ADMIN_HOME_SUCCESS";


export const ADMIN_USER_BLOCK_REQUSET = "ADMIN_USER_BLOCK_REQUSET";
export const ADMIN_USER_BLOCK_SUCCESS = " ADMIN_USER_BLOCK_SUCCESS";
export const ADMIN_USER_BLOCK_FAIL = "ADMIN_USER_BLOCK_FAIL";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";


export const ADMIN_SEARCH_REQUEST = "ADMIN_SEARCH_REQUEST ";
export const ADMIN_SEARCH_SUCCESS = "ADMIN_SEARCH_SUCCESS ";
export const ADMIN_SEARCH_FAIL = "ADMIN_SEARCH_FAIL ";
